apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: explorage-hpa
  namespace: explorage
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: explorage-backend
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
